addons:
  apt:
    packages:
      - clang
      - libc++-dev
      - libc++abi-dev
      - libglfw3-dev
      - libglu1-mesa-dev
      - libopengl-dev
      - libunwind-dev
      - libunwind8
      - libxcursor-dev
      - libxcursor1
      - libxi-dev
      - libxi6
      - libxinerama-dev
      - libxinerama1
      - libxrandr-dev
      - libxrandr2
      - lld
      - lldb
      - llvm-dev
      - llvm-runtime
      - ninja-build
    update: true
dist: focal
env:
  matrix:
    - TOOL=cmake
    - TOOL=make
language: cpp
notifications:
  email: false
os:
  - linux
script:
  - env TOOL=$TOOL make
