jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -yqq
          sudo apt-get install -yqq \
            lsb-release \
            software-properties-common \
            wget
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt-get update
          sudo apt-get upgrade -yqq
          sudo apt-get install -yqq \
            libc++-14-dev \
            libc++abi-14-dev \
            libglfw3-dev \
            libglu1-mesa-dev \
            libopengl-dev \
            libunwind-14-dev \
            libxcursor-dev \
            libxcursor1 \
            libxi-dev \
            libxi6 \
            libxinerama-dev \
            libxinerama1 \
            libxrandr-dev \
            libxrandr2
      - name: Build
        run: |
          env \
            PATH="/usr/lib/llvm-14/bin:$PATH" \
            TOOL=make \
            make -j13
name: Build
on:
  pull_request:
    paths-ignore:
      - '**.ico'
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'ReadMe.txt'
      - 'glfw.rc'
      - 'glfw.sln'
      - 'glfw.vcxproj'
      - 'glfw.vcxproj.filters'
      - 'packages.config'
      - 'resource.h'
  push:
    paths-ignore:
      - '**.ico'
      - '**.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'ReadMe.txt'
      - 'glfw.rc'
      - 'glfw.sln'
      - 'glfw.vcxproj'
      - 'glfw.vcxproj.filters'
      - 'packages.config'
      - 'resource.h'
